name: unity_ads_mediation
description: Unity Mediation is a plugin for Flutter Applications. This plugin is able to display and Unity Rewarded Ads and Interstitial Ads.
version: 2.0.0
homepage: https://github.com/AnmolSethi/unity_ads_mediation
repository: https://github.com/AnmolSethi/unity_ads_mediation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: anmolsethi.dev.unity_ads_mediation
        pluginClass: UnityAdsMediationPlugin
